export const data = [
  {
    key: 1,
    name: "Hackathon",
    prize: 60000,
    Imgsrc: require("./files/hackathon.jpg"),
    link: "https://www.nitj.ac.in/events_registration/hackmol/login",
    visit: "https://hackmol.tech/",
    desc: "HackMOL is the flagship annual 30-hour hackathon being organised by Google Developer Student (GDSC) of NIT Jalandhar...",
  },
  {
    key: 2,
    name: "chemecar",
    prize: 10000,
    Imgsrc: require("./files/hackathon.jpg"),
    regLink: "https://l01vlmq5gan.typeform.com/to/zGwKjZLG",
    link: "chemecar",
    desc: "Chem-e-Car engages college students in designing and constructing a car powered by a chemical energy...",
  },
  {
    key: 3,
    name: "chemedesign",
    prize: 10000,
    Imgsrc: require("./files/hackathon.jpg"),
    link: "chemedesign",
    desc: "The event will be organised in two parts Designing the heat exchanger  Presenting the technical ...",
  },
  {
    key: 4,
    name: "prayaas",
    prize: 3000,
    Imgsrc: require("./files/hackathon.jpg"),
    link: "prayaas",
    desc: "To educate underprivileged and socially marginalized youth who lack access to education, especially those who are the...",
  },
  {
    key: 5,
    name: "gaNIT",
    prize: 5500,
    Imgsrc: require("./files/hackathon.jpg"),
    link: "maths",
    desc: "The Integration Bee is an annual traditional playoff-style event that has gained popularity in US colleges and universities...",
  },
  {
    key: 6,
    name: "robohunt",
    prize: 3000,
    Imgsrc: require("./files/hackathon.jpg"),
    link: "robohunt",
    desc: "Robo Hunt is a competition where teams will write the code of controller of small robots, known as bots, that are less than 6 kg...",
  },
  {
    key: 7,
    name: "microrobowar",
    prize: 8000,
    Imgsrc: require("./files/hackathon.jpg"),
    link: "microrobowar",
    desc: "Micro Robo War is a robot fighting competition where contestant teams will compete head-to-head in a 1 vs 1 match...",
  },

  {
    key: 8,
    name: "trickycircuits",
    prize: 5000,
    Imgsrc: require("./files/hackathon.jpg"),
    link: "trickycircuits",
    desc: "Tricky Circuits is a competition where participants will be given circuits consisting of resistors, gates, and ...",
  },
  {
    key: 9,
    name: "3BHK",
    prize: "Momentos & Goodies",
    Imgsrc: require("./files/hackathon.jpg"),
    link: "threebhk",
    desc: "The Aim of the event is to teach the students about the practical application of building construction...",
  },
  {
    key: 10,
    name: "uavdrone",
    prize: "",
    Imgsrc: require("./files/hackathon.jpg"),
    link: "uavdrone",
    desc: "Drones are objects that the world is looking up to. TechNITi'23 presents the UAV Drone challange, A multi-level ...",
  },
  {
    key: 11,
    name: "robowar",
    prize: "",
    Imgsrc: require("./files/hackathon.jpg"),
    link: "robowar",
    desc: "It will be a savage, Clash of Metals with the alloys grinding red hot. It is a game of style, control, damage and  ...",
  },
  {
    key: 12,
    name: "RCcars",
    prize: "",
    Imgsrc: require("./files/hackathon.jpg"),
    link: "rccars",
    desc: "RC car event, a fight of machines and a test of endurance, persistence and strength of the car. There will be a ...",
  },
  {
    key: 13,
    name: "atv Racing",
    prize: "",
    Imgsrc: require("./files/hackathon.jpg"),
    link: "avishkar",
    desc: "Our self-manufactured ATV is exhibited in fully running condition and workshop would be commanded by various...",
  },
  {
    key: 14,
    name: "RC cars",
    prize: "",
    Imgsrc: require("./files/hackathon.jpg"),
    link: "https://l01vlmq5gan.typeform.com/to/zGwKjZLG",
    desc: "",
  },
  {
    key: 15,
    name: "bolt-bolt",
    prize: 10500,
    Imgsrc: require("./files/hackathon.jpg"),
    link: "https://l01vlmq5gan.typeform.com/to/zGwKjZLG",
    desc: "",
  },
  {
    key: 16,
    name: "lumentrace",
    prize: 10500,
    Imgsrc: require("./files/hackathon.jpg"),
    link: "lumenTrace",
    desc: "",
  },
  {
    key: 17,
    name: "smart tank",
    prize: 10500,
    Imgsrc: require("./files/hackathon.jpg"),
    link: "smarttank",
    desc: "",
  },
];
